function lims = sero_pulseq_sysLims_prisma()
% function lims = sero_pulseq_sysLims_prisma()
%
% Here, I hope that we can use three sets of limits so that we can optimize
% imaging, diffusion, and spoiling gradients separately.

B0 = 2.89;
deadTime = 10e-6;

% Set system limits for imaging
lims.img = mr.opts('MaxGrad',45,'GradUnit','mT/m',...
                   'MaxSlew',170,'SlewUnit','T/m/s',...
                   'rfRingdownTime', 10e-6, 'rfDeadtime', 100e-6,...
                   'adcDeadTime', deadTime, 'B0', B0);

% Set system limits for diffusion encoding
lims.diff = mr.opts('MaxGrad',78,'GradUnit','mT/m',...
                    'MaxSlew',90,'SlewUnit','T/m/s',...
                    'rfRingdownTime', 10e-6, 'rfDeadtime', 100e-6,...
                    'adcDeadTime', deadTime, 'B0', B0);

% Set system limits for spoilers
lims.spl = mr.opts('MaxGrad',50,'GradUnit','mT/m',...
                   'MaxSlew',20,'SlewUnit','T/m/s',...
                   'rfRingdownTime', 10e-6, 'rfDeadtime', 100e-6,...
                   'adcDeadTime', deadTime, 'B0', B0);
